import keyword

cpp = ['case', 'abstract', 'typedef', 'function', 'require', 'argc', 'endswitch', 'double', 'protected', 'assert', 'endfor', 'do', 'const', 'parent', 'elif', 'final', 'require_once', 'HTTP_COOKIE_VARS', 'pass', 'xor', 'inline', 'for', 'False', 'not', 'PHP_OS', 'wchar_t', 'this', 'auto', 'namespace', 'extends', 'lambda', 'with', 'endforeach', 'stdClass', 'from', 'if', 'nonlocal', 'export', 'exit', 'del', 'die', 'goto', 'while', 'external', 'static', 'sync', 'E_WARNING', 'finally', 'void', 'switch', 'print', 'in', 'throw', '__FILE__', '__wakeup', 'new', 'TRUE', 'short', '__LINE__', 'include', 'extern', 'async', 'await', 'typename', 'is', 'unsigned', 'char', '__sleep', 'else', 'using', 'reinterpret_cast', 'yield', 'foreach', 'break', 'def', 'true', 'delete', 'typeid', 'endif', 'sizeof', 'union', 'names', 'True', 'HTTP_POST_FILES', 'HTTP_ENV_VARS', 'continue', 'or', 'bool', 'asm', 'HTTP_POST_VARS', 'PHP_VERSION', 'virtual', 'FALSE', 'empty', 'public', 'var', 'PHP_SELF', 'catch', 'implements', 'factory', 'rethrow', 'float', 'enum', 'dynamic', 'deferred', 'None', 'argv', 'E_ERROR', 'E_ALL', 'E_PARSE', 'static_cast', 'explicit', 'get', 'struct', 'operator', 'register', 'default', 'class', 'template', 'library', 'raise', 'echo', 'list', 'global', 'except', 'HTTP_GET_VARS', 'and', 'import', 'try', 'endwhile', 'friend', 'HTTP_SERVER_VARS', 'mutable', 'return', 'as', 'set', 'elseif', 'null', 'long', 'private', 'false', 'signed', 'dynamic_cast',
 'part', 'int', 'include_once', 'volatile', 'NULL', 'const_cast', 'super']

html = ['<a>', '<abbr>', '<address>', '<area>', '<article>', '<aside>', '<audio>', '<b>', '<base>', '<bdi>', '<bdo>', '<blockquote>', '<body>', '<br>', '<button>', '<canvas>', '<caption>', '<cite>', '<code>', '<col>', '<colgroup>', '<data>', '<datalist>', '<dd>', '<del>', '<dfn>', '<div>', '<dl>', '<dt>', '<em>', '<embed>', '<fieldset>', '<figcaption>', '<figure>', '<footer>', '<form>', '<h1>', '<->', '<h6>', '<head>', '<header>', '<hr>', '<html>', '<i>', '<iframe>', '<img>', '<input>', '<ins>', '<kbd>', '<keygen>', '<label>', '<legend>',
        '<li>', '<link>', '<main>', '<map>', '<mark>', '<meta>', '<meter>', '<nav>', '<noscript>', '<object>', '<ol>', '<optgroup>', '<option>', '<output>', '<p>', '<param>', '<pre>', '<progress>', '<q>', '<rb>', '<rp>', '<rt>', '<rtc>', '<ruby>', '<s>', '<samp>', '<script>', '<section>', '<select>', '<small>', '<source>', '<span>', '<strong>', '<style>', '<sub>', '<sup>', '<table>', '<tbody>', '<td>', '<template>', '<textarea>', '<tfoot>', '<th>', '<thead>', '<time>', '<title>', '<tr>', '<track>', '<u>', '<ul>', '<var>', '<video>', '<wbr>']
        

php = ['argv', 'argc', 'break', 'case', 'class', 'continue', 'default', 'do', 'die', 'echo', 'else', 'elseif', 'empty', 'endfor', 'endforeach', 'endif', 'endswitch', 'endwhile', 'E_ALL', 'E_PARSE', 'E_ERROR', 'E_WARNING', 'exit', 'extends', 'FALSE', 'for', 'foreach', 'function', 'HTTP_COOKIE_VARS', 'HTTP_GET_VARS', 'HTTP_POST_VARS', 'HTTP_POST_FILES',
 'HTTP_ENV_VARS', 'HTTP_SERVER_VARS', 'if', 'include', 'include_once', 'global', 'list', 'new', 'not', 'NULL', 'or', 'parent', 'PHP_OS', 'PHP_SELF', 'PHP_VERSION', 'print', 'require', 'require_once', 'return', 'static', 'switch', 'stdClass', 'this', 'TRUE', 'var', 'xor', 'virtual', 'while', '__FILE__', '__LINE__', '__sleep', '__wakeup']
dart = ['abstract', 'continue', 'false', 'new', 'this', 'as', 'default', 'final', 'null', 'throw', 'assert', 'deferred', 'finally', 'operator', 'true', 'async', 'do', 'for', 'part', 'try', 'async', 'dynamic', 'get', 'rethrow', 'typedef', 'await', 'else', 'if', 'return',
 'var', 'break', 'enum', 'implements', 'set', 'void', 'case', 'export', 'import', 'static', 'while', 'catch', 'external', 'in', 'super', 'with', 'class', 'extends', 'is', 'switch', 'yield', 'const', 'factory', 'library', 'sync', 'yield']

print(list(set(cpp+html+php+dart+keyword.kwlist)))